# Generated by Django 4.2.1 on 2023-12-15 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=255, verbose_name='Department name')),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Profession title')),
            ],
            options={
                'verbose_name_plural': 'Professions',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name='Full Name')),
                ('birthday', models.DateField(verbose_name='Bithday')),
                ('stardet_day', models.DateField(verbose_name='Started Day')),
                ('working_for', models.CharField(blank=True, max_length=255, null=True, verbose_name='Working For')),
                ('languages', models.CharField(blank=True, max_length=255, null=True, verbose_name='Languages')),
                ('another_country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Another Country')),
                ('deputy', models.CharField(blank=True, max_length=255, null=True, verbose_name='Deputy')),
                ('party_member', models.CharField(blank=True, max_length=255, null=True, verbose_name='Party Member')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone Number')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Profile Photo')),
                ('prev_place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Prev Place')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='staff.department', verbose_name='Department')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profession', to='staff.profession', verbose_name='Profession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Staff',
            },
        ),
    ]
