# Generated by Django 4.2.1 on 2023-12-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staff_birthday_alter_staff_stardet_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name'),
        ),
    ]
