# Generated by Django 4.2.8 on 2024-01-15 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0004_alter_staff_fullname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="staff",
            old_name="stardet_day",
            new_name="started_day",
        ),
    ]
